export const PHOTOS_REQUEST = 'PHOTOS_REQUEST';
export const PHOTOS_SUCCESS = 'PHOTOS_SUCCESS';
export const PHOTOS_FAILURE = 'PHOTOS_FAILURE';

export const SELECTED_PHOTOS_REQUEST = 'SELECTED_PHOTOS_REQUEST';
export const SELECTED_PHOTOS_SUCCESS = 'SELECTED_PHOTOS_SUCCESS';
export const SELECTED_PHOTOS_FAILURE = 'SELECTED_PHOTOS_FAILURE';
